[package]
name = "mwps"
version = "0.0.0"
authors = ["Yue Wu <wuyue16pku@gmail.com>"]
edition = "2021"
license = "MIT"
description = "Hypergraph Minimum-Weight Parity Subgraph (MWPS) Solver for Quantum LDPC Codes"
readme = "README.md"
homepage = "https://hyper-mwps.com"
repository = "https://github.com/yuewuo/mwps"
keywords = ["QEC", "quantum-computing", "error-correction", "visualization"]
categories = ["science"]
exclude = [
    "tutorial/*",
    "benchmark/*",
    "visualize/data/persist/*",
    ".github/*",
]

# see https://doc.rust-lang.org/1.39.0/cargo/reference/manifest.html#the-documentation-field-optional
[badges]
maintenance = { status = "actively-developed" }

[lib]
name = "mwps"
path = "src/lib.rs"
crate-type = ["lib", "cdylib"]

[[bin]]
name = "mwps"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# profiling: see scripts/NOTES.md

# embed debug symbols
[profile.release]
debug = true

[features]
# to enable a feature, use `--features xxx`
default = []
python_binding = ["pyo3"]  # bind to Python

[dependencies]
pyo3 = { version =  "0.18.3", features = ["extension-module", "multiple-pymethods", "abi3-py37"], optional = true }
serde = { version = "1.0.117", features = ["derive", "rc"] }
serde_json = "1.0.59"
chrono = "0.4.19"
urlencoding = "2.1.0"
clap = { version = "4.2.7", features = ["cargo", "derive"] }
pbr = "1.0.4"
rand_xoshiro = "0.6.0"
derivative = "2.2.0"
parking_lot = { version = "0.12.1", features = ["hardware-lock-elision"] }
num-rational = "0.4.1"
num-traits = "0.2.15"
more-asserts = "0.3.1"
rand = "0.8.5"
prettytable-rs = "0.10.0"
itertools = "0.10.5"

[package.metadata.docs.rs]
rustdoc-args = [ "--html-in-header", "katex-header.html" ]
# to run locally: `RUSTDOCFLAGS="--html-in-header katex-header.html" cargo doc --no-deps`
